# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiau', '0022_materiau_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('site_web', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('brouillon', models.BooleanField()),
                ('nom_produit', models.CharField(blank=True, max_length=255, verbose_name='Nom du produit')),
                ('fabrication', models.TextField(blank=True, null=True, verbose_name='Procédé de fabrication')),
                ('mise_en_forme', models.TextField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='packagings')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packaging.Marque')),
                ('materiaux', models.ManyToManyField(blank=True, to='materiau.Materiau')),
            ],
        ),
        migrations.CreateModel(
            name='Brouillon',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Brouillons',
                'proxy': True,
                'indexes': [],
            },
            bases=('packaging.packaging',),
        ),
        migrations.CreateModel(
            name='PackagingApprouve',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Packagings approuvés',
                'proxy': True,
                'indexes': [],
            },
            bases=('packaging.packaging',),
        ),
    ]
