# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
