# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0007_add_default_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='finition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packaging.Finition'),
        ),
    ]
