# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituent', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=2, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usage', models.TextField(default='N.R.')),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='materiaux')),
            ],
            options={
                'verbose_name': 'Materiau',
                'verbose_name_plural': 'Materiaux',
            },
        ),
        migrations.CreateModel(
            name='SubFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituent', models.CharField(max_length=255)),
                ('ref_number', models.IntegerField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiau.Family')),
            ],
        ),
        migrations.AddField(
            model_name='materiau',
            name='sub_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiau.SubFamily'),
        ),
    ]
