# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sousfamille',
            options={'verbose_name': 'Sous famille', 'verbose_name_plural': 'Sous Familles'},
        ),
        migrations.AlterField(
            model_name='materiau',
            name='usage',
            field=models.TextField(blank=True, default='N.R.', null=True),
        ),
        migrations.AlterField(
            model_name='sousfamille',
            name='matiere',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
