# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0002_auto_20170811_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brouillon',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Brouillons',
                'proxy': True,
                'indexes': [],
            },
            bases=('materiau.materiau',),
        ),
        migrations.CreateModel(
            name='MateriauApprouve',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Materiaux approuvés',
                'proxy': True,
                'indexes': [],
            },
            bases=('materiau.materiau',),
        ),
        migrations.AddField(
            model_name='materiau',
            name='brouillon',
            field=models.BooleanField(default=False),
        ),
    ]
