# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0004_auto_20170812_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('unite', models.CharField(default='N.R.', max_length=30, verbose_name='unité')),
                ('definition', models.TextField(default='N.R.', verbose_name='définition')),
                ('type', models.CharField(blank=True, choices=[('thermodynamique', 'thermodynamique'), ('mécanique', 'mécanique')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
            },
        ),
    ]
