# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0005_propriete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(blank=True, choices=[('générale', 'générale'), ('thermique', 'thermodynamique'), ('mécanique', 'mécanique'), ('électrique', 'électrique'), ('environnemental', 'environnemental')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='unite',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='unité'),
        ),
    ]
