# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0006_auto_20170812_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('qualificatif', models.CharField(blank=True, max_length=255, null=True)),
                ('materiau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiau.Materiau', verbose_name='matériau')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiau.Propriete', verbose_name='propriété')),
            ],
            options={
                'verbose_name': 'Attribut',
                'verbose_name_plural': 'Attributs',
            },
        ),
    ]
