# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0007_attribut'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormeMarchande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='materiau',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribut',
            name='propriete',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='materiau.Propriete', verbose_name='propriété'),
        ),
        migrations.AddField(
            model_name='materiau',
            name='forme_marchande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiau.FormeMarchande'),
        ),
    ]
