# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0009_add_default_forme_marchande'),
    ]

    operations = [
        migrations.AddField(
            model_name='formemarchande',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
