# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0015_materiau_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('qualificatif', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='materiau',
            name='aspect',
            field=models.ManyToManyField(blank=True, null=True, to='materiau.Aspect'),
        ),
    ]
