# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0017_add_default_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiau',
            name='aspect',
            field=models.ManyToManyField(blank=True, to='materiau.Aspect'),
        ),
    ]
