# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0019_add_default_propriete'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiau',
            name='empreinte_ecologique',
            field=models.CharField(blank=True, choices=[('élevée', 'élevée'), ('moyenne', 'moyenne'), ('faible', 'faible')], max_length=255, verbose_name='Empreinte écologique'),
        ),
        migrations.AddField(
            model_name='materiau',
            name='fin_de_vie',
            field=models.CharField(blank=True, choices=[('déchet toxique', 'déchet toxique'), ('recyclable', 'recyclable'), ('valorisable', 'valorisable'), ('biodégradable', 'biodégradable')], max_length=255),
        ),
        migrations.AddField(
            model_name='materiau',
            name='origine',
            field=models.CharField(blank=True, choices=[('synthétique', 'synthétique'), ('naturelle', 'naturelle'), ('bio-sourcé', 'bio-sourcé'), ('recyclé', 'recyclé')], max_length=255),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(blank=True, choices=[('générale', 'générale'), ('thermodynamique', 'thermodynamique'), ('mécanique', 'mécanique'), ('électrique', 'électrique'), ('environnemental', 'environnemental')], max_length=255, null=True),
        ),
    ]
