# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0020_auto_20170927_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiau',
            name='classement_au_feu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materiau',
            name='classement_ecologique',
            field=models.TextField(blank=True, null=True, verbose_name='Classement écologique'),
        ),
        migrations.AddField(
            model_name='materiau',
            name='classement_humidite',
            field=models.TextField(blank=True, null=True, verbose_name="Classement à l'humidité"),
        ),
    ]
