# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiau', '0021_auto_20170927_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiau',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
